### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by nilanjansiromani** [relative-ci/bundle-stats#626]
We get an  error when trying to compare two jsons
```
➜  product git:(bundle-stats-comparison) ✗ bundbundle-stats  --html  ./bundleStats/baseline.json ./bundleStats/bundle-stats.json 
  ✔ Read Webpack stats files
  ↓ Read baseline data [skipped]
    → Multiple stat files already set.
  ↓ Write baseline data [skipped]
    → Not a baseline job (see --baseline).
  ✖ Process data
    → Cannot read property 'split' of undefined
    Generate reports
    Save reports
TypeError: Cannot read property 'split' of undefined
    at getAssetName (/Users/n0s00jx/codebase/work/product/node_modules/@bundle-stats/utils/lib/assets/get-asset-name.js:17:35)
    at /Users/n0s00jx/codebase/work/product/node_modules/@bundle-stats/utils/lib/transforms/assets-webpack-transform.js:49:45
    at Array.reduce (<anonymous>)
    at assetsWebpackTransform (/Users/n0s00jx/codebase/work/product/node_modules/@bundle-stats/utils/lib/transforms/assets-webpack-transform.js:44:32)
    at createStats (/Users/n0s00jx/codebase/work/product/node_modules/@bundle-stats/utils/lib/stats/create.js:97:82)
    at createJob (/Users/n0s00jx/codebase/work/product/node_modules/@bundle-stats/utils/lib/jobs/create-job.js:53:41)
    at /Users/n0s00jx/codebase/work/product/node_modules/@bundle-stats/utils/lib/jobs/create-jobs.js:28:126
    at Array.reduce (<anonymous>)
    at createJobs (/Users/n0s00jx/codebase/work/product/node_modules/@bundle-stats/utils/lib/jobs/create-jobs.js:28:53)
    at Task.task (/Users/n0s00jx/codebase/work/product/node_modules/bundle-stats/bin/run.js:84:27) {
  context: [Object: null prototype] { artifacts: [ [Object], [Object] ] }
}
```

**Comment by vio** [comment]
Hi @nilanjansiromani, thanks for raising this!

Will try to investigate, but can you please share more details about your setup ?
1. version of bundle-stats / webpack / node
2. any errors when running `bundle-stats --demo`
3. webpack stats files

**Comment by vio** [comment]
@nilanjansiromani I was able to replicate the error when passing invalid webpack stats. The latest  version ([2.2.0](https://github.com/relative-ci/bundle-stats/releases/tag/v2.2.0)) is going to validate the entire structure and give you an error message.

Feel free to re-open this issue if you still have problems.
